# Generated by Django 6.0.6 on 2026-06-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'ganancia'), ('egreso', 'gasto')], max_length=7),
        ),
    ]
